### ISSUE TITLE
`pactffi_register_plugin_log_callback` is uncallable from C — cbindgen emits `Option<PluginLogCallback>` as an opaque struct passed by value

### ISSUE THREAD

**Issue by JP-Ellis** [pact-foundation/pact-reference#544]
**Affects:** pact-ffi 0.5.5 (introduced by #537, `feat(008): Plugin observability`)

### Summary

The generated `pact.h` declares:

```c
typedef struct Option_PluginLogCallback Option_PluginLogCallback;   /* line 317 */

void pactffi_register_plugin_log_callback(struct Option_PluginLogCallback callback);  /* line 4776 */
```

`Option_PluginLogCallback` is only ever forward-declared — it is an *incomplete* type — yet it
is passed **by value**. A C or C++ caller cannot define a value of an incomplete type, so there
is no way to construct the argument. The function is therefore impossible to call from the
public header.

Note the header still *compiles* when merely included; the failure occurs only at the call site.

### Reproduction

```c
#include "pact.h"
extern "C" void cb(const char*, const char*, const char*, const char*, const char*) {}
int main(void) { pactffi_register_plugin_log_callback(cb); return 0; }
```

```
error: no matching function for call to 'pactffi_register_plugin_log_callback'
note: candidate function not viable: no known conversion from
      'void (const char *, const char *, const char *, const char *, const char *)'
      to 'struct Option_PluginLogCallback' for 1st argument
```

### Root cause

The Rust side is correct — this is purely a header-generation problem.

`rust/pact_ffi/src/log/plugin_sink.rs:14`:

```rust
pub type PluginLogCallback = unsafe extern "C" fn(
  plugin_instance_id: *const c_char,
  test_run_id: *const c_char,
  level: *const c_char,
  target: *const c_char,
  message: *const c_char,
);
```

`rust/pact_ffi/src/plugins/mod.rs:190`:

```rust
pub extern "C" fn pactffi_register_plugin_log_callback(callback: Option<PluginLogCallback>)
```

`Option<fn-pointer>` benefits from the null-pointer optimisation, so the actual ABI is already a
plain nullable function pointer. cbindgen did not resolve the `PluginLogCallback` alias (it is
declared in a different module from the FFI function) and so treated `Option<PluginLogCallback>`
as a generic instantiation, emitting it as an opaque type.

### Expected header output

```c
void pactffi_register_plugin_log_callback(
  void (*callback)(const char*, const char*, const char*, const char*, const char*));
```

### Suggested fix

Make cbindgen expand the alias — e.g. move/re-export `PluginLogCallback` so cbindgen can resolve
it, add it to the cbindgen config, or take the raw function-pointer type directly at the FFI
boundary.

### Workaround for consumers

Because the ABI is already correct, a consumer can hand-declare the prototype rather than using
the generated typedef, and it will link and run correctly. This is fragile — the signature must
be kept in sync manually — so we have not adopted it in pact-js-core.
